### ISSUE TITLE
缺货状态的在订单详情页点击加载没有反应

### ISSUE THREAD

**Issue by zmlasn** [qwqoffice/woocommerce-to-wechatapp-mini#1]
在首页缺货的会提示到不能添加到购物车验库存，但是到详情页就没有验库存了，点击无反馈

**Comment by qwqoffice** [comment]
![image](https://user-images.githubusercontent.com/18651085/56416641-0f38bf00-62c4-11e9-81a8-70bf7003ee7e.png)
删除/pages/product-detail/product-detail.js 中红框内容即可
