### ISSUE TITLE
待付款订单调取支付

### ISSUE THREAD

**Issue by zmlasn** [qwqoffice/woocommerce-to-wechatapp-mini#2]
在订单列表待付款的会调取默认选择我的支付方式给到反馈，但是在订单详情页待付款的点击支付显示正在加载后就没有对应的支付反馈了

**Comment by qwqoffice** [comment]
没有复现到，列表和详情都是可以支付

**Comment by zmlasn** [comment]
我这边是仅配置微信支付但是没有填写具体的支付商户信息，然后在订单提交页面以及列表页会提示“当前订单支付暂时出现问题，请稍后重试”，但是在订单详情页没有处理-以下为错误内容showToast:fail parameter error: parameter.title should be String instead of Undefined;

**Comment by zmlasn** [comment]
![image](https://user-images.githubusercontent.com/35757192/56419297-532fc200-62cc-11e9-842f-08d313c797e6.png)

**Comment by qwqoffice** [comment]
app.js 309行 改为 `if (paymentData.fail) paymentData.fail({errMsg:data.msg});`
