### ISSUE TITLE
图片加载缓慢整体渲染性能不佳

### ISSUE THREAD

**Issue by zmlasn** [qwqoffice/woocommerce-to-wechatapp-mini#3]
能否在图片展示上加上图片预载和加载失败补偿机制，目前动态渲染的性能过分依赖于网络环境，整体体验不是很好

**Comment by qwqoffice** [comment]
哪个部分的图片

**Comment by zmlasn** [comment]
就是首页产品图和分类的图片，没加载成功之前撑开老大一块加载完之后才能展示正常目前

**Comment by qwqoffice** [comment]
可在`app.wxss`中加入以下样式解决
```
image {
	height: 0;
}
```

**Comment by zmlasn** [comment]
![WechatIMG1380](https://user-images.githubusercontent.com/35757192/58855970-ed5c9580-86d3-11e9-8cbb-430ee667be61.jpeg)
像这种，感觉还是有点违和，没加载好就很尴尬，最好还是引用下默认图

**Comment by qwqoffice** [comment]
设置一个适合的高度即可
